# Generated by Django 5.2.17 on 2026-08-14 14:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(default=1, help_text='Curriculum day index')),
                ('title', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('learn', 'Learn Concept'), ('understand', 'Personal Understanding'), ('practice', 'Coding Practice'), ('review', 'Revision & Doubts'), ('complete', 'Milestone Checkoff')], default='learn', max_length=20)),
                ('description', models.TextField()),
                ('estimated_minutes', models.PositiveIntegerField(default=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='learning.learningpath')),
                ('topic_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_tasks', to='learning.topic')),
            ],
            options={
                'ordering': ['day_number', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PracticeProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('platform', models.CharField(choices=[('learninghub', 'LearningHub Practice'), ('leetcode', 'LeetCode'), ('hackerrank', 'HackerRank'), ('codewars', 'Codewars')], default='learninghub', max_length=20)),
                ('problem_url', models.URLField(blank=True, max_length=500)),
                ('prompt_description', models.TextField()),
                ('starter_code', models.TextField(blank=True, default='# Write your solution here\n')),
                ('solution_hint', models.TextField(blank=True)),
                ('solution_code', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_problems', to='learning.topic')),
            ],
            options={
                'ordering': ['topic__level__level_number', 'topic__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserDailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('date_assigned', models.DateField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('daily_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_instances', to='progress.dailytask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_daily_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['daily_task__order'],
                'unique_together': {('user', 'daily_task', 'date_assigned')},
            },
        ),
        migrations.CreateModel(
            name='UserPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('solved', 'Solved')], default='not_started', max_length=20)),
                ('my_solution_code', models.TextField(blank=True)),
                ('reflection_notes', models.TextField(blank=True, help_text='Key takeaways, time complexity, or tricks learned')),
                ('time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempts', to='progress.practiceproblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'problem')},
            },
        ),
        migrations.CreateModel(
            name='UserTopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('understanding_level', models.CharField(choices=[('not_started', 'Not Started'), ('learning', 'Learning (Getting familiar)'), ('need_revision', 'Need Revision (Shaky / Confused)'), ('comfortable', 'Comfortable (Can use in code)'), ('strong', 'Strong (Can teach to others)')], default='not_started', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('times_reviewed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['topic__level__level_number', 'topic__order'],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
