# Generated by Django 5.2.17 on 2026-08-14 14:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True, help_text='What are you aiming to build with Python?')),
                ('primary_goal', models.CharField(choices=[('beginner', 'Python from Absolute Zero'), ('internship', 'Internship & Job Interview Prep'), ('software_eng', 'Software Engineering Fundamentals'), ('data_science', 'Data Science & Automation Foundation'), ('college_exam', 'College Coursework & Lab Prep')], default='beginner', max_length=50)),
                ('experience_level', models.CharField(choices=[('zero', 'Complete Beginner (No prior coding)'), ('some', 'Know basic programming (C/C++/Java)'), ('rusty', 'Used Python before, need structured refresher'), ('intermediate', 'Intermediate, want to master core concepts')], default='zero', max_length=50)),
                ('daily_goal_minutes', models.PositiveIntegerField(default=45, help_text='Target minutes per day')),
                ('current_streak', models.PositiveIntegerField(default=1)),
                ('longest_streak', models.PositiveIntegerField(default=1)),
                ('last_active_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
