# Generated by Django 5.2.17 on 2026-08-14 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tagline', models.CharField(default='Master Python from zero to job-ready', max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='code', help_text='Icon identifier (e.g., terminal, code, cpu)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='learning.learningpath')),
            ],
            options={
                'ordering': ['level_number', 'order'],
                'unique_together': {('learning_path', 'level_number')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_minutes', models.PositiveIntegerField(default=30)),
                ('objectives', models.TextField(help_text='Bullet points separated by newlines')),
                ('summary_content', models.TextField(help_text='In-depth conceptual explanation for students')),
                ('code_snippet', models.TextField(blank=True, help_text='Clean Python code example demonstrating the topic')),
                ('key_takeaways', models.TextField(blank=True, help_text='Key takeaways separated by newlines')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learning.level')),
            ],
            options={
                'ordering': ['level__level_number', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('video', 'Video Tutorial'), ('doc', 'Official Documentation'), ('article', 'In-Depth Article'), ('practice', 'Interactive Practice'), ('cheatsheet', 'Cheat Sheet / Reference')], default='doc', max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('author_or_source', models.CharField(default='Python Official Docs', max_length=150)),
                ('duration_or_read_time', models.CharField(default='10 min read', max_length=50)),
                ('is_recommended', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='learning.topic')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='learning.resource')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'resource')},
            },
        ),
    ]
