# Generated by Django 5.2.17 on 2026-08-14 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningDoubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubt_text', models.TextField(help_text='What question or doubt do you still have about this topic?')),
                ('resolution_notes', models.TextField(blank=True, help_text='How was this doubt resolved? What was the answer?')),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubts', to='learning.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_resolved', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistake_description', models.TextField(help_text='What mistake or error did you make while writing or practicing?')),
                ('correction_or_lesson', models.TextField(help_text='What is the fix or rule to avoid this in the future?')),
                ('error_type', models.CharField(choices=[('syntax', 'Syntax Error'), ('logic', 'Logic / Off-by-one Bug'), ('runtime', 'Runtime / Exception'), ('type', 'Type Mismatch / Conversion'), ('conceptual', 'Conceptual Misunderstanding'), ('name', 'NameError / Scope Mistake')], default='syntax', max_length=30)),
                ('code_snippet', models.TextField(blank=True, help_text='The broken vs corrected code snippet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='learning.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Quick Note', max_length=255)),
                ('content', models.TextField()),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags (e.g. syntax, trick, interview)', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='learning.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalLearningMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_i_understood', models.TextField(blank=True, help_text='Summarize the concept in your own natural words.')),
                ('my_own_explanation', models.TextField(blank=True, help_text='Explain this concept as if you were teaching it to a 10-year-old.')),
                ('real_life_analogy', models.TextField(blank=True, help_text='What real-world comparison makes this click for you?')),
                ('my_code_example', models.TextField(blank=True, help_text='Your own custom Python snippet demonstrating this topic.')),
                ('what_confused_me', models.TextField(blank=True, help_text='What parts felt tricky, confusing, or easy to mix up?')),
                ('what_helped_me', models.TextField(blank=True, help_text="What unlocked the 'aha!' moment for you?")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_memories', to='learning.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
