# Generated by Django 5.2.17 on 2026-08-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role_or_college', models.CharField(default='Computer Science Student', max_length=150)),
                ('avatar_color', models.CharField(default='#3B82F6', max_length=20)),
                ('initials', models.CharField(default='JD', max_length=5)),
                ('quote', models.TextField()),
                ('outcome', models.CharField(help_text="e.g. 'Cracked Python Internship at TechCorp'", max_length=150)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Student Story',
                'verbose_name_plural': 'Student Stories',
                'ordering': ['order', 'id'],
            },
        ),
    ]
