# Generated by Django 5.2.17 on 2026-08-14 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Python 30-Day Intensive Bootcamp', max_length=150)),
                ('slug', models.SlugField(default='python-30-day-bootcamp', unique=True)),
                ('tagline', models.CharField(default='Go from absolute beginner to building real Python projects in 30 days', max_length=255)),
                ('description', models.TextField()),
                ('total_days', models.PositiveIntegerField(default=30)),
                ('icon', models.CharField(default='rocket', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BootcampDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('concept_summary', models.TextField()),
                ('learning_goals', models.TextField(help_text='Bullet points separated by newlines')),
                ('practice_assignment', models.TextField(help_text='The practical challenge for today')),
                ('code_starter', models.TextField(blank=True)),
                ('estimated_minutes', models.PositiveIntegerField(default=60)),
                ('resource_url', models.URLField(blank=True, max_length=500)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='bootcamp.bootcamp')),
                ('topic_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bootcamp_days', to='learning.topic')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('bootcamp', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='UserBootcampProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('submission_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bootcamp_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='bootcamp.bootcampday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootcamp_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['bootcamp_day__day_number'],
                'unique_together': {('user', 'bootcamp_day')},
            },
        ),
    ]
