# Generated by Django 5.2.17 on 2026-08-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentorArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('strategy', 'Learning Strategy & Consistency'), ('debugging', 'Debugging & Problem Solving'), ('interview', 'Python Internship & Interview Prep'), ('mistakes', 'Avoiding Beginner Pitfalls'), ('projects', 'Resume Projects & Building Things')], default='strategy', max_length=30)),
                ('author_name', models.CharField(default='LearningHub Senior Mentors', max_length=100)),
                ('read_time_minutes', models.PositiveIntegerField(default=5)),
                ('summary', models.TextField()),
                ('content', models.TextField(help_text='Full article guide content')),
                ('actionable_rules', models.TextField(help_text='Key actionable rules separated by newlines')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_tip', models.TextField()),
                ('category', models.CharField(default='Daily Wisdom', max_length=50)),
                ('icon', models.CharField(default='lightbulb', max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
